/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Inplementacion.DAOProductosImpl;
import intefazDAO.DAOProductos;
import javax.swing.JOptionPane;
import tablas.CProductos;

/**
 *
 * @author Esteban Rodriguez
 */
public class Editar extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
        setLocationRelativeTo(null);
        //esta linea hace que se sierra la ventana emergente sin cerrar la app
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    public void cargarDatos(CProductos producto) {
// Configurar los campos de texto u otros componentes con los detalles del producto
        txtId.setText(String.valueOf(producto.getId()));
        txtNombre.setText(producto.getCategoria());
        txtDescripcion.setText(producto.getDescripcion());
        txtIva.setText(String.valueOf(producto.getIVA()));
        txtCompra.setText(String.valueOf(producto.getPrecioCompra()));
        txtVenta.setText(String.valueOf(producto.getPrecioVenta()));

        txtId.setEditable(false);
    }

    private boolean esEntero() {
        try {
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        tituloId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        tituloNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        tituloCompra = new javax.swing.JLabel();
        txtCompra = new javax.swing.JTextField();
        tituloIva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        tituloVenta = new javax.swing.JLabel();
        txtVenta = new javax.swing.JTextField();
        tituloDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("EDITAR PRODUCTO");

        tituloId.setText("ID");

        tituloNombre.setText("NOMBRE");

        tituloCompra.setText("PRECIO COMPRA");

        tituloIva.setText("IVA");

        tituloVenta.setText("PRECIO VENTA");

        tituloDescripcion.setText("DESCRIPCION");

        btnRegistrar.setText("Editar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtVenta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(tituloId, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(tituloCompra)))
                            .addComponent(tituloVenta))
                        .addGap(28, 28, 28)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tituloDescripcion)
                            .addComponent(tituloIva)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(tituloNombre)
                            .addComponent(txtIva)
                            .addComponent(txtDescripcion)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(btnRegistrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(37, 37, 37)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloId)
                    .addComponent(tituloNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCompra)
                    .addComponent(tituloIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloVenta)
                    .addComponent(tituloDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            String id = txtId.getText();
            String nombre = txtNombre.getText();
            String descripcion = txtDescripcion.getText();
            String precioCompraStr = txtCompra.getText();
            String ivaStr = txtIva.getText();
            String precioVentaStr = txtVenta.getText();

            boolean todasLasValidacionesExitosas = true;

            if (id.isEmpty() || nombre.isEmpty() || descripcion.isEmpty() || precioCompraStr.isEmpty()
                    || ivaStr.isEmpty() || precioVentaStr.isEmpty()) {
                // Mostrar un mensaje de error o realizar alguna acción si algún campo está vacío
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                todasLasValidacionesExitosas = false;
            }
            CProductos producto = new CProductos();
            producto.setCategoria(nombre);
            producto.setDescripcion(descripcion);

            // Convertir las cadenas a los tipos de datos adecuados y validar
            if (esEntero()) {
                int inId = Integer.parseInt(id);
                producto.setId(inId);

            } else {
                todasLasValidacionesExitosas = false;
            }
            if (esEntero()) {
                int precioCompra = Integer.parseInt(precioCompraStr);
                producto.setPrecioCompra(precioCompra);

            } else {
                todasLasValidacionesExitosas = false;
            }
            if (esEntero()) {
                int iva = Integer.parseInt(ivaStr);
                producto.setIVA(iva);

            } else {
                todasLasValidacionesExitosas = false;
            }

            if (esEntero()) {
                int precioVenta = Integer.parseInt(precioVentaStr);
                producto.setPrecioVenta(precioVenta);

            } else {
                todasLasValidacionesExitosas = false;
            }

            if (todasLasValidacionesExitosas) {
                try {
                    DAOProductos dao = new DAOProductosImpl();
                    dao.editar(producto);
                    JOptionPane.showMessageDialog(this, "Producto editado correctamente.",
                            "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } catch (Exception e) {

                }
            } else {

            }
        } catch (Exception e) {
            String mensaje = e.getMessage();

            // String mensajeUsuario = "no se puede registrar el producto por que los valores de ID, PRECIO O IVA son INVALIDOS";
            JOptionPane.showMessageDialog(this, mensaje,
                    "MENSAJE INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloCompra;
    private javax.swing.JLabel tituloDescripcion;
    private javax.swing.JLabel tituloId;
    private javax.swing.JLabel tituloIva;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloVenta;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
